CREATE TABLE [dbo].[BarrowersInformation]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ApplicantsPersonalInformationId] INT NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL, 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [MiddleName] NVARCHAR(50) NULL, 
    [Suffix] NVARCHAR(50) NULL, 
    [Citizenship] VARCHAR(50) NULL, 
    [BirthDate] DATETIME2 NULL,
    [Sex] NVARCHAR(20) NULL, 
    [MaritalStatus] VARCHAR(50) NULL, 
    [HomeNumber] NVARCHAR(50) NULL, 
    [MobileNumber] NVARCHAR(50) NULL, 
    [PagibigMidNumber] NVARCHAR(MAX) NULL, 
    [HanNumber] NVARCHAR(MAX) NULL, 
    [Email] NVARCHAR(100) NULL, 
    [IsPermanentAddressAbroad] BIT NULL DEFAULT(0), 
    [IsPresentAddressAbroad] BIT NULL DEFAULT(0), 
    [IsBusinessAddressAbroad] BIT NULL DEFAULT(0),
    [PresentUnitName] NVARCHAR(255) NULL,
    [PresentBuildingName] NVARCHAR(255) NULL,
    [PresentLotName] NVARCHAR(255) NULL,
    [PresentStreetName] NVARCHAR(255) NULL,
    [PresentSubdivisionName] NVARCHAR(255) NULL,
    [PresentBaranggayName] NVARCHAR(255) NULL,
    [PresentMunicipalityName] NVARCHAR(255) NULL,
    [PresentProvinceName] NVARCHAR(255) NULL,
    [PresentZipCode] NVARCHAR(255) NULL,
    [PermanentUnitName] NVARCHAR(255) NULL,
    [PermanentBuildingName] NVARCHAR(255) NULL,
    [PermanentLotName] NVARCHAR(255) NULL,
    [PermanentStreetName] NVARCHAR(255) NULL,
    [PermanentSubdivisionName] NVARCHAR(255) NULL,
    [PermanentBaranggayName] NVARCHAR(255) NULL,
    [PermanentMunicipalityName] NVARCHAR(255) NULL,
    [PermanentProvinceName] NVARCHAR(255) NULL,
    [PermanentZipCode] NVARCHAR(255) NULL,
    [HomeOwnerShip] NVARCHAR(255) NULL,
    [YearsofStay] INT NULL,
    [SSSNumber] NVARCHAR(150) NULL,
    [TinNumber] NVARCHAR(150) NULL,
    [OccupationStatus] NVARCHAR(100) NULL,
    [EmployerName] NVARCHAR(100) NULL,
    [IndustryName] NVARCHAR(100) NULL,
    [PositionName] NVARCHAR(100) NULL,
    [DepartmentName] NVARCHAR(100) NULL,
    [YearsEmployment] INT NULL,
    [NumberOfDependent] INT NULL,
    [BusinessUnitName] NVARCHAR(255) NULL,
    [BusinessBuildingName] NVARCHAR(255) NULL,
    [BusinessLotName] NVARCHAR(255) NULL,
    [BusinessStreetName] NVARCHAR(255) NULL,
    [BusinessSubdivisionName] NVARCHAR(255) NULL,
    [BusinessBaranggayName] NVARCHAR(255) NULL,
    [BusinessMunicipalityName] NVARCHAR(255) NULL,
    [BusinessProvinceName] NVARCHAR(255) NULL,
    [BusinessZipCode] NVARCHAR(255) NULL,
    [BusinessCountry] NVARCHAR(255) NULL,
    [BusinessContactNumber] NVARCHAR(20) NULL,
    [BusinessDirectLineNumber] NVARCHAR(50) NULL,
    [BusinessTruckLineNumber] NVARCHAR(50) NULL,
    [BusinessEmail] NVARCHAR(255) NULL,
    [PreparedMailingAddress] NVARCHAR(255) NULL,
    [PreferredTimeToContact] NVARCHAR(100) NULL,
    [DateCreated] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
    [CreatedById] INT NOT NULL, 
    [DateModified] DATETIME2 NULL, 
    [ModifiedById] INT NULL,
    [DateDeleted] DATETIME2 NULL, 
    [DeletedById] INT NULL,
    PropertyDeveloperName NVARCHAR(255) NULL,
    PropertyLocation NVARCHAR(255) NULL,
    PropertyUnitLevelName NVARCHAR(255) NULL,
    MonthlyRent DECIMAL(18,2) NULL
)
