 IF NOT EXISTS (SELECT 1 FROM [dbo].[Module])
BEGIN
SET IDENTITY_INSERT [dbo].[Module] ON 
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (1, 3, 1, NULL, N'Home', N'Home', N'Dashboard', N'fe-airplay', N'Home', N'Index', 1, 1, CAST(N'2024-02-21T08:33:57.3364362' AS DateTime2), 1, NULL, NULL, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (2, 3, 2, NULL, N'Module', N'Module  Management', N'Modules', N'mdi mdi-view-module', N'Module', N'Index', 1, 1, CAST(N'2024-02-21T08:34:29.3336588' AS DateTime2), 1, CAST(N'2024-02-23T10:25:21.4593468' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (3, 3, 3, 4, N'UserRole', N'User Role Management', N'User Role', N'fe-users', N'Role', N'UserRole', 0, 1, CAST(N'2024-02-23T00:26:01.9113401' AS DateTime2), 1, CAST(N'2024-02-23T06:24:13.5894635' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (4, 3, 4, NULL, N'Role', N'Role Management', N'Role Setup', N'fe-grid', N'Role', N'Index', 1, 0, CAST(N'2024-02-23T01:31:34.8887491' AS DateTime2), 1, CAST(N'2024-02-24T05:07:29.5110261' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (5, 3, 5, NULL, N'Applicants', N'Applicants Setup', N'Applicants', N'mdi mdi-folder-multiple', NULL, NULL, 1, 1, CAST(N'2024-02-23T01:49:01.4075453' AS DateTime2), 1, CAST(N'2024-02-24T05:13:11.7122192' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (6, 3, 7, NULL, N'Profile', N'Profile Setup', N'Profile', N'mdi mdi-account', N'Account', N'Profile', 0, 1, CAST(N'2024-02-23T03:27:47.1358295' AS DateTime2), 1, CAST(N'2024-02-23T06:24:27.8520512' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (19, 3, 10, NULL, N'Faqs', N'FAQS', N'FAQS', N'mdi mdi-information-outline', NULL, NULL, 0, 0, CAST(N'2024-02-23T04:59:34.1487957' AS DateTime2), 1, CAST(N'2024-02-23T05:09:08.1131752' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (20, 3, 8, 5, N'HLF068', N'HOUSING LOAN APPLICATION', N'Loan Application', N'mdi mdi-file-document-multiple', N'Applicants', N'HLF068', 0, 1, CAST(N'2024-02-23T06:36:56.4926905' AS DateTime2), 1, CAST(N'2024-02-24T03:56:42.2345171' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (21, 3, 9, 5, N'Document', N'Document Setup', N'Documents', N'mdi mdi-file-document-multiple', N'Document', N'Index', 1, 1, CAST(N'2024-02-23T07:23:43.1113407' AS DateTime2), 1, CAST(N'2024-02-24T06:40:05.9038249' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (22, 3, 1, 5, N'Beneficiary', N'Beneficiary Management', N'Beneficiary', N'mdi mdi-format-list-text', N'Applicants', N'Index', 1, 1, CAST(N'2024-02-24T05:11:21.6948360' AS DateTime2), 1, CAST(N'2024-02-24T05:16:36.3193701' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (23, 3, 1, 22, N'ApplicantRequests', N'Application Management', N'Applicant Requests', N'mdi mdi-file-edit', N'Applicants', N'ApplicantRequests', 0, 1, CAST(N'2024-02-24T15:17:29.0498651' AS DateTime2), 1, CAST(N'2024-02-25T01:39:48.8648786' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (24, 3, 1, 20, N'DocumentUpload', N'Document Upload', N'Document Upload', N'mdi-file-upload', N'Document', N'DocumentUpload', 0, 1, CAST(N'2024-02-25T07:38:51.1053080' AS DateTime2), 1, CAST(N'2024-02-25T07:41:20.8506280' AS DateTime2), 1, NULL, NULL)
INSERT [dbo].[Module] ([Id], [ModuleStatusId], [Ordinal], [ParentModuleId], [Code], [BreadName], [Description], [Icon], [Controller], [Action], [IsVisible], [IsBreaded], [DateCreated], [CreatedById], [DateModified], [ModifiedById], [DateDeleted], [DeletedById]) VALUES (25, 3, 1, null, N'Company', N'Company Profile', N'Company Profile', N'mdi-file', N'Company', N'Index', 0, 1, CAST(N'2024-02-25T07:38:51.1053080' AS DateTime2), 1, CAST(N'2024-02-25T07:41:20.8506280' AS DateTime2), 1, NULL, NULL)

SET IDENTITY_INSERT [dbo].[Module] OFF
END
GO