CREATE TABLE [dbo].[BeneficiaryInformation]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	UserId INT NOT NULL,
	PagibigNumber NVARCHAR(255),
    Code NVARCHAR(255),
	CompanyId INT NULL,
	LastName NVARCHAR(150),
	FirstName NVARCHAR(150),
	MiddleName NVARCHAR(150),
	BirthDate DATETIME2(7) NULL,
	Age INT NULL,
	MobileNumber NVARCHAR(50) NULL,
	Sex NVARCHAR(50),
	[IsPermanentAddressAbroad] BIT NULL DEFAULT(0), 
    [IsPresentAddressAbroad] BIT NULL DEFAULT(0), 
    [PresentUnitName] NVARCHAR(255) NULL,
    [PresentBuildingName] NVARCHAR(255) NULL,
    [PresentLotName] NVARCHAR(255) NULL,
    [PresentStreetName] NVARCHAR(255) NULL,
    [PresentSubdivisionName] NVARCHAR(255) NULL,
    [PresentBaranggayName] NVARCHAR(255) NULL,
    [PresentMunicipalityName] NVARCHAR(255) NULL,
    [PresentProvinceName] NVARCHAR(255) NULL,
    [PresentZipCode] NVARCHAR(50) NULL,
    [PermanentUnitName] NVARCHAR(255) NULL,
    [PermanentBuildingName] NVARCHAR(255) NULL,
    [PermanentLotName] NVARCHAR(255) NULL,
    [PermanentStreetName] NVARCHAR(255) NULL,
    [PermanentSubdivisionName] NVARCHAR(255) NULL,
    [PermanentBaranggayName] NVARCHAR(255) NULL,
    [PermanentMunicipalityName] NVARCHAR(255) NULL,
    [PermanentProvinceName] NVARCHAR(255) NULL,
    [PermanentZipCode] NVARCHAR(50) NULL,

    PropertyDeveloperId INT,
    PropertyUnitId INT,
    PropertyLocationId INT,
    PropertyProjectId INT,

    CreatedById INT NULL,
    DateCreated DATETIME2(7) NOT NULL DEFAULT(GETDATE()),
    ModifiedById INT NULL,
    DateModified DATETIME2(7) NULL,
    Email NVARCHAR(255) NULL, 
    [IsBcfCreated] BIT NOT NULL DEFAULT 0
)