// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class Address
{
    public int Id { get; set; }

    public int ReferenceId { get; set; }

    /// <summary>
    /// Company = 1, Vendor = 2, Customer = 3, Employee = 3
    /// </summary>
    public int ReferenceType { get; set; }

    public string StreetAddress1 { get; set; }

    public string StreetAddress2 { get; set; }

    public string Baranggay { get; set; }

    public string CityMunicipality { get; set; }

    public string Municipality { get; set; }

    public string Province { get; set; }

    public string StateProvince { get; set; }

    public string Region { get; set; }

    public int PostalCode { get; set; }

    public int? CountryId { get; set; }

    public string Remarks { get; set; }

    public bool IsDisabled { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int ModifiedById { get; set; }

    public DateTime DateModified { get; set; }

    public bool? IsDefault { get; set; }

    public string AddressName { get; set; }
}