// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class ApprovalLevel
{
    public int Id { get; set; }

    public int ApprovalStatusId { get; set; }

    public int Status { get; set; }

    public int ApproverId { get; set; }

    /// <summary>
    /// ApprovalLevel
    /// </summary>
    public int Level { get; set; }

    public string Remarks { get; set; }

    public DateTime DateUpdated { get; set; }

    public int? ModuleStageId { get; set; }
}