// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class AuditTrailRef
{
    public int Id { get; set; }

    public string ColumnName { get; set; }

    public string ColumnDisplay { get; set; }
}