// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class AuditTrailHeader
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int? UserId { get; set; }

    public DateTime DateCreated { get; set; }
}