// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class BeneficiaryInformation
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string PagibigNumber { get; set; }

    public string Code { get; set; }

    public int? CompanyId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public DateTime? BirthDate { get; set; }

    public int? Age { get; set; }

    public string MobileNumber { get; set; }

    public string Sex { get; set; }

    public bool? IsPermanentAddressAbroad { get; set; }

    public bool? IsPresentAddressAbroad { get; set; }

    public string PresentUnitName { get; set; }

    public string PresentBuildingName { get; set; }

    public string PresentLotName { get; set; }

    public string PresentStreetName { get; set; }

    public string PresentSubdivisionName { get; set; }

    public string PresentBaranggayName { get; set; }

    public string PresentMunicipalityName { get; set; }

    public string PresentProvinceName { get; set; }

    public string PresentZipCode { get; set; }

    public string PermanentUnitName { get; set; }

    public string PermanentBuildingName { get; set; }

    public string PermanentLotName { get; set; }

    public string PermanentStreetName { get; set; }

    public string PermanentSubdivisionName { get; set; }

    public string PermanentBaranggayName { get; set; }

    public string PermanentMunicipalityName { get; set; }

    public string PermanentProvinceName { get; set; }

    public string PermanentZipCode { get; set; }

    public int? PropertyDeveloperId { get; set; }

    public int? PropertyUnitId { get; set; }

    public int? PropertyLocationId { get; set; }

    public int? PropertyProjectId { get; set; }

    public int? CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }

    public string Email { get; set; }

    public bool IsBcfCreated { get; set; }
}