// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class BuyerConfirmation
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Code { get; set; }

    public string PagibigNumber { get; set; }

    public string ProjectProponentName { get; set; }

    public int? JuridicalPersonalityId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Suffix { get; set; }

    public DateTime? BirthDate { get; set; }

    public string MothersMaidenName { get; set; }

    public string MaritalStatus { get; set; }

    public string OccupationStatus { get; set; }

    public string PresentUnitName { get; set; }

    public string PresentBuildingName { get; set; }

    public string PresentLotName { get; set; }

    public string PresentStreetName { get; set; }

    public string PresentSubdivisionName { get; set; }

    public string PresentBaranggayName { get; set; }

    public string PresentMunicipalityName { get; set; }

    public string PresentProvinceName { get; set; }

    public string PresentZipCode { get; set; }

    public string HomeNumber { get; set; }

    public string MobileNumber { get; set; }

    public string BusinessTelNo { get; set; }

    public string Email { get; set; }

    public string CompanyEmployerName { get; set; }

    public string CompanyUnitName { get; set; }

    public string CompanyBuildingName { get; set; }

    public string CompanyLotName { get; set; }

    public string CompanyStreetName { get; set; }

    public string CompanySubdivisionName { get; set; }

    public string CompanyBaranggayName { get; set; }

    public string CompanyMunicipalityName { get; set; }

    public string CompanyProvinceName { get; set; }

    public string CompanyZipCode { get; set; }

    public decimal? AffordMonthlyAmortization { get; set; }

    public string SpouseLastName { get; set; }

    public string SpouseFirstName { get; set; }

    public string SpouseMiddleName { get; set; }

    public string SpouseSuffix { get; set; }

    public string SpouseCompanyEmployerName { get; set; }

    public string SpouseCompanyUnitName { get; set; }

    public string SpouseCompanyBuildingName { get; set; }

    public string SpouseCompanyLotName { get; set; }

    public string SpouseCompanyStreetName { get; set; }

    public string SpouseCompanySubdivisionName { get; set; }

    public string SpouseCompanyBaranggayName { get; set; }

    public string SpouseCompanyMunicipalityName { get; set; }

    public string SpouseCompanyProvinceName { get; set; }

    public string SpouseCompanyZipCode { get; set; }

    public decimal? SpouseMonthlySalary { get; set; }

    public decimal? MonthlySalary { get; set; }

    public bool IsOtherSourceOfIncome { get; set; }

    public string AdditionalSourceIncome { get; set; }

    public decimal? AverageMonthlyAdditionalIncome { get; set; }

    public bool IsPagibigMember { get; set; }

    public bool IsPagibigCoBorrower { get; set; }

    public bool IsPursueProjectProponent { get; set; }

    public bool IsInformedTermsConditions { get; set; }

    public bool IsPagibigAvailedLoan { get; set; }

    public string HouseUnitModel { get; set; }

    public decimal? SellingPrice { get; set; }

    public decimal? MonthlyAmortization { get; set; }

    public DateTime? DateCreated { get; set; }

    public int? CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public int? ApprovalStatus { get; set; }

    public int? CompanyId { get; set; }

    public int? PropertyDeveloperId { get; set; }

    public int? PropertyProjectId { get; set; }

    public int? ProjectUnitId { get; set; }

    public int? PropertyLocationId { get; set; }
}