// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class BuyerConfirmationDocument
{
    public int Id { get; set; }

    public int? ReferenceId { get; set; }

    public string ReferenceNo { get; set; }

    public int? Status { get; set; }

    public string Remarks { get; set; }

    public int? CreatedById { get; set; }

    public DateTime? DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }
}