// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class CollateralInformation
{
    public int Id { get; set; }

    public int ApplicantsPersonalInformationId { get; set; }

    public string Province { get; set; }

    public string Municipality { get; set; }

    public string Street { get; set; }

    public string DeveloperName { get; set; }

    public int? PropertyTypeId { get; set; }

    public string TctOctCctNumber { get; set; }

    public string TaxDeclrationNumber { get; set; }

    public int? LotUnitNumber { get; set; }

    public int? BlockBuildingNumber { get; set; }

    public bool? IsMortgage { get; set; }

    public string CollateralReason { get; set; }

    public decimal? LandArea { get; set; }

    public int? HouseAge { get; set; }

    public int? NumberOfStoreys { get; set; }

    public int? ProposedNoOfStoreys { get; set; }

    public decimal? ExistingTotalFloorArea { get; set; }

    public decimal? ProposedTotalFloorArea { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateDeleted { get; set; }

    public int? DeletedById { get; set; }
}