// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class DocumentType
{
    public int Id { get; set; }

    public string Description { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateDeleted { get; set; }

    public int? DeletedById { get; set; }

    public virtual ICollection<DocumentVerification> DocumentVerifications { get; set; } = new List<DocumentVerification>();
}