// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class EmailLog
{
    public int Id { get; set; }

    public int ReferenceId { get; set; }

    public string ReferenceNo { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int SenderId { get; set; }

    public int ReceiverId { get; set; }

    public DateTime Date { get; set; }
}