// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class EmailSetup
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Host { get; set; }

    public string DisplayName { get; set; }

    public int Port { get; set; }

    public int CompanyId { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public bool IsDefault { get; set; }
}