// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class FileType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string format { get; set; }
}