// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class LoanParticularsInformation
{
    public int Id { get; set; }

    public int ApplicantsPersonalInformationId { get; set; }

    public int RepricingPeriod { get; set; }

    public int PurposeOfLoanId { get; set; }

    public int ModeOfPaymentId { get; set; }

    public int DesiredLoanTermYears { get; set; }

    public decimal DesiredLoanAmount { get; set; }

    public string ExistingHousingApplicationNumber { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateDeleted { get; set; }

    public int? DeletedById { get; set; }

    public bool? IsEnrolledToMRI { get; set; }

    public string PaymentScheme { get; set; }
}