// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class LockedTransaction
{
    public int Id { get; set; }

    public int? ModuleId { get; set; }

    public string TransactionNo { get; set; }

    public int TransactionId { get; set; }

    public int UserId { get; set; }

    public DateTime LastActivity { get; set; }
}