// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Template.Domain.Entities;

public partial class Module
{
    public int Id { get; set; }

    public int ModuleStatusId { get; set; }

    public int? Ordinal { get; set; }

    public int? ParentModuleId { get; set; }

    public string Code { get; set; }

    public string BreadName { get; set; }

    public string Description { get; set; }

    public string Icon { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public bool IsVisible { get; set; }

    public bool IsBreaded { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedById { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateDeleted { get; set; }

    public int? DeletedById { get; set; }
}