// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class NotificationReceiver
{
    public int Id { get; set; }

    public int NotifId { get; set; }

    public int ReceiverId { get; set; }

    public int ReceiverType { get; set; }

    public bool IsRead { get; set; }

    public DateTime DateRead { get; set; }

    public bool IsDelete { get; set; }

    public virtual Notification Notif { get; set; }
}