// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class Notification
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Preview { get; set; }

    public string ActionLink { get; set; }

    public bool IsRead { get; set; }

    public DateTime DateCreated { get; set; }

    public int CompanyId { get; set; }

    public int SenderId { get; set; }

    public int PriorityLevel { get; set; }

    public int NotificationType { get; set; }

    public virtual ICollection<NotificationReceiver> NotificationReceivers { get; set; } = new List<NotificationReceiver>();
}