// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class Report
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public byte[] LayoutData { get; set; }
}