// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class SubDocument
{
    public int Id { get; set; }

    public int? DocumentTypeId { get; set; }

    public int? Type { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public int? ParentId { get; set; }
}