// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class TemporaryLink
{
    public int Id { get; set; }

    public Guid GuId { get; set; }

    public int? UserId { get; set; }

    public bool? IsSubmitted { get; set; }

    public DateTime? DateSubmitted { get; set; }

    public bool? IsOpened { get; set; }

    public DateTime? DateExpiration { get; set; }
}