// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class UserActivity
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Action { get; set; }

    public DateTime Date { get; set; }

    public string Browser { get; set; }

    public string Device { get; set; }

    public int ActivityTypeId { get; set; }
}