// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DMS.Domain.Entities;

public partial class vwTransaction
{
    public int ReferenceId { get; set; }

    public string ReferenceNo { get; set; }

    public int? ModuleId { get; set; }

    public int? CompanyId { get; set; }

    public int CreatedById { get; set; }

    public DateTime DateCreated { get; set; }

    public int? ModifiedById { get; set; }

    public DateTime? DateModified { get; set; }

    public string ModuleController { get; set; }

    public string ModuleAction { get; set; }

    public string ModuleCode { get; set; }

    public bool? WithApprover { get; set; }
}