CREATE TABLE [dbo].[CollateralInformation]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ApplicantsPersonalInformationId] INT NOT NULL,
    [Province] NVARCHAR(250) NOT NULL,
    [Municipality] NVARCHAR(250) NOT NULL,
    [Street] NVARCHAR(250) NOT NULL,
    [DeveloperName] NVARCHAR(250) NOT NULL,
    [PropertyTypeId] INT NOT NULL,
    [TctOctCctNumber] INT NULL,
    [TaxDeclrationNumber] INT NULL,
    [LotUnitNumber] INT NULL,
    [BlockBuildingNumber] INT NULL,
    [IsMortgage] BIT NULL,
    [CollateralReason] NVARCHAR(MAX) NOT NULL,
    [LandArea] DECIMAL(18, 2) NULL,
    [HouseAge] INT NULL,
    [NumberOfStoreys] INT NULL,
    [ProposedNoOfStoreys] INT NULL,
    [ExistingTotalFloorArea] DECIMAL(18, 2) NULL,
    [ProposedTotalFloorArea] DECIMAL(18, 2) NULL,
    [DateCreated] DATETIME2 NOT NULL DEFAULT (GETDATE()), 
    [CreatedById] INT NOT NULL, 
    [DateModified] DATETIME2 NULL, 
    [ModifiedById] INT NULL,
    [DateDeleted] DATETIME2 NULL, 
    [DeletedById] INT NULL
)
